name: CI
on:
  pull_request:
    branches: [master, development, next]
  push:
    branches: [master, development, next]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_READONLY }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_PKG_READONLY }}
      - name: Lint Files
        run: yarn test-lint
  jest:
    name: Jest
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_READONLY }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_PKG_READONLY }}
      - name: Run Unit Tests
        run: yarn test-unit
  e2e:
    name: End<->End
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [jest]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PKG_READONLY }}" >> ~/.npmrc
          echo "@algodex:registry=https://npm.pkg.github.com" >> ~/.npmrc
          yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_PKG_READONLY }}
      - name: Run End to End Tests
        run: yarn test
  release:
    name: Release Package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    needs: [ e2e ]
    steps:
      - run: echo Need to implement Release Cycle
